export enum ObjectNameEnum {
    VM = "vm",
    RG = "rg",
    DISK = "disk",
    NSG = "nsg",
    VIRTUALNETWORK = "virtualNetwork",
    NETWORKINTERFACE = "networkInterfaces",
    NAMESPACE = "namespaces",
    PODS = "pods",
    HELM = "helm",
    AKS = "aks",
    REPOSITORIES = "repositories",
    BRANCHES = "branches",
    ISSUES = "issues",
    IP = "ip",
    PUBLICIP = "PublicIp",
    EC2INSTANCE = "ec2Instance",
    EC2VOLUME = "ec2Volume",
    EC2SG = "ec2SG",
    RDS = "rds",
    RESOURCEGROUPS = "resourceGroups",
    TAGSVALUE = "tagsValue",
    ECSCLUSTER = "ecsCluster",
    ECRIMAGE = "ecrImage",
    BUCKET = "bucket",
    TASK = "task",
    COMPUTE = "compute"
}