#!/bin/bash
# add all packages to the project
bun add @aws-sdk/client-accessanalyzer
bun add @aws-sdk/client-account
bun add @aws-sdk/client-acm
bun add @aws-sdk/client-acm-pca
bun add @aws-sdk/client-alexa-for-business
bun add @aws-sdk/client-amp
bun add @aws-sdk/client-amplify
bun add @aws-sdk/client-amplifybackend
bun add @aws-sdk/client-amplifyuibuilder
bun add @aws-sdk/client-api-gateway
bun add @aws-sdk/client-apigatewaymanagementapi
bun add @aws-sdk/client-app-mesh
bun add @aws-sdk/client-appconfig
bun add @aws-sdk/client-appflow
bun add @aws-sdk/client-appintegrations
bun add @aws-sdk/client-application-auto-scaling
bun add @aws-sdk/client-application-insights
bun add @aws-sdk/client-applicationcostprofiler
bun add @aws-sdk/client-apprunner
bun add @aws-sdk/client-appstream
bun add @aws-sdk/client-appsync
bun add @aws-sdk/client-athena
bun add @aws-sdk/client-auditmanager
bun add @aws-sdk/client-auto-scaling
bun add @aws-sdk/client-auto-scaling-plans
bun add @aws-sdk/client-backup
bun add @aws-sdk/client-backup-gateway
bun add @aws-sdk/client-batch
bun add @aws-sdk/client-billingconductor
bun add @aws-sdk/client-braket
bun add @aws-sdk/client-budgets
bun add @aws-sdk/client-chime
bun add @aws-sdk/client-chime-sdk-identity
bun add @aws-sdk/client-chime-sdk-media-pipelines
bun add @aws-sdk/client-chime-sdk-meetings
bun add @aws-sdk/client-chime-sdk-messaging
bun add @aws-sdk/client-cloudcontrol
bun add @aws-sdk/client-clouddirectory
bun add @aws-sdk/client-cloudformation
bun add @aws-sdk/client-cloudfront
bun add @aws-sdk/client-cloudhsm
bun add @aws-sdk/client-cloudsearch
bun add @aws-sdk/client-cloudsearch-domain
bun add @aws-sdk/client-cloudtrail
bun add @aws-sdk/client-cloudwatch
bun add @aws-sdk/client-cloudwatch-events
bun add @aws-sdk/client-cloudwatch-logs
bun add @aws-sdk/client-codeartifact
bun add @aws-sdk/client-codebuild
bun add @aws-sdk/client-codecommit
bun add @aws-sdk/client-codedeploy
bun add @aws-sdk/client-codeguru-reviewer
bun add @aws-sdk/client-codeguruprofiler
bun add @aws-sdk/client-codepipeline
bun add @aws-sdk/client-codestar
bun add @aws-sdk/client-codestar-connections
bun add @aws-sdk/client-codestar-notifications
bun add @aws-sdk/client-cognito-identity
bun add @aws-sdk/client-cognito-identity-provider
bun add @aws-sdk/client-cognito-sync
bun add @aws-sdk/client-commander
bun add @aws-sdk/client-comprehend
bun add @aws-sdk/client-comprehendmedical
bun add @aws-sdk/client-compute-optimizer
bun add @aws-sdk/client-connect
bun add @aws-sdk/client-connect-contact-lens
bun add @aws-sdk/client-connectcampaigns
bun add @aws-sdk/client-connectparticipant
bun add @aws-sdk/client-cost-explorer
bun add @aws-sdk/client-customer-profiles
bun add @aws-sdk/client-data-pipeline
bun add @aws-sdk/client-databrew
bun add @aws-sdk/client-dataexchange
bun add @aws-sdk/client-datasync
bun add @aws-sdk/client-dax
bun add @aws-sdk/client-detective
bun add @aws-sdk/client-device-farm
bun add @aws-sdk/client-devops-guru
bun add @aws-sdk/client-direct-connect
bun add @aws-sdk/client-dlm
bun add @aws-sdk/client-docdb
bun add @aws-sdk/client-drs
bun add @aws-sdk/client-dynamodb
bun add @aws-sdk/client-dynamodb-streams
bun add @aws-sdk/client-ebs
bun add @aws-sdk/client-ec2
bun add @aws-sdk/client-ecr
bun add @aws-sdk/client-ecr-public
bun add @aws-sdk/client-ecs
bun add @aws-sdk/client-efs
bun add @aws-sdk/client-eks
bun add @aws-sdk/client-elastic-beanstalk
bun add @aws-sdk/client-elastic-inference
bun add @aws-sdk/client-elastic-load-balancing
bun add @aws-sdk/client-elastic-transcoder
bun add @aws-sdk/client-elasticache
bun add @aws-sdk/client-emr
bun add @aws-sdk/client-emr-containers
bun add @aws-sdk/client-emr-serverless
bun add @aws-sdk/client-eventbridge
bun add @aws-sdk/client-evidently
bun add @aws-sdk/client-finspace
bun add @aws-sdk/client-firehose
bun add @aws-sdk/client-fis
bun add @aws-sdk/client-fms
bun add @aws-sdk/client-forecast
bun add @aws-sdk/client-forecastquery
bun add @aws-sdk/client-frauddetector
bun add @aws-sdk/client-fsx
bun add @aws-sdk/client-gamelift
bun add @aws-sdk/client-gamesparks
bun add @aws-sdk/client-glacier
bun add @aws-sdk/client-global-accelerator
bun add @aws-sdk/client-glue
bun add @aws-sdk/client-grafana
bun add @aws-sdk/client-greengrass
bun add @aws-sdk/client-groundstation
bun add @aws-sdk/client-guardduty
bun add @aws-sdk/client-health
bun add @aws-sdk/client-healthlake
bun add @aws-sdk/client-honeycode
bun add @aws-sdk/client-iam
bun add @aws-sdk/client-identitystore
bun add @aws-sdk/client-imagebuilder
bun add @aws-sdk/client-inspector
bun add @aws-sdk/client-iot
bun add @aws-sdk/client-iot-data-plane
bun add @aws-sdk/client-iot-events
bun add @aws-sdk/client-iot-jobs-data-plane
bun add @aws-sdk/client-iot-wireless
bun add @aws-sdk/client-iotanalytics
bun add @aws-sdk/client-iotdeviceadvisor
bun add @aws-sdk/client-iotfleethub
bun add @aws-sdk/client-iotsecuretunneling
bun add @aws-sdk/client-iotsitewise
bun add @aws-sdk/client-iotthingsgraph
bun add @aws-sdk/client-iottwinmaker
bun add @aws-sdk/client-ivs
bun add @aws-sdk/client-ivschat
bun add @aws-sdk/client-kafka
bun add @aws-sdk/client-kafkaconnect
bun add @aws-sdk/client-kendra
bun add @aws-sdk/client-keyspaces
bun add @aws-sdk/client-kinesis
bun add @aws-sdk/client-kinesis-analytics
bun add @aws-sdk/client-kinesis-video
bun add @aws-sdk/client-kinesis-video-archived-media
bun add @aws-sdk/client-kinesis-video-media
bun add @aws-sdk/client-kinesis-video-signaling
bun add @aws-sdk/client-kms
bun add @aws-sdk/client-lakeformation
bun add @aws-sdk/client-lambda
bun add @aws-sdk/client-lex-runtime-service
bun add @aws-sdk/client-license-manager
bun add @aws-sdk/client-lightsail
bun add @aws-sdk/client-location
bun add @aws-sdk/client-lookoutequipment
bun add @aws-sdk/client-lookoutmetrics
bun add @aws-sdk/client-lookoutvision
bun add @aws-sdk/client-machine-learning
bun add @aws-sdk/client-macie
bun add @aws-sdk/client-managedblockchain
bun add @aws-sdk/client-marketplace-commerce-analytics
bun add @aws-sdk/client-marketplace-metering
bun add @aws-sdk/client-mediaconnect
bun add @aws-sdk/client-mediaconvert
bun add @aws-sdk/client-medialive
bun add @aws-sdk/client-mediapackage
bun add @aws-sdk/client-mediapackage-vod
bun add @aws-sdk/client-mediastore
bun add @aws-sdk/client-mediatailor
bun add @aws-sdk/client-memorydb
bun add @aws-sdk/client-mgn
bun add @aws-sdk/client-migration-hub
bun add @aws-sdk/client-migration-hub-refactor-spaces
bun add @aws-sdk/client-migrationhub-config
bun add @aws-sdk/client-migrationhubstrategy
bun add @aws-sdk/client-mobile
bun add @aws-sdk/client-mq
bun add @aws-sdk/client-mturk
bun add @aws-sdk/client-mwaa
bun add @aws-sdk/client-neptune
bun add @aws-sdk/client-network-firewall
bun add @aws-sdk/client-networkmanager
bun add @aws-sdk/client-nimble
bun add @aws-sdk/client-opensearch
bun add @aws-sdk/client-opsworks
bun add @aws-sdk/client-opsworkscm
bun add @aws-sdk/client-organizations
bun add @aws-sdk/client-outposts
bun add @aws-sdk/client-panorama
bun add @aws-sdk/client-personalize
bun add @aws-sdk/client-personalize-events
bun add @aws-sdk/client-personalize-runtime
bun add @aws-sdk/client-pi
bun add @aws-sdk/client-pinpoint
bun add @aws-sdk/client-pinpoint-email
bun add @aws-sdk/client-pinpoint-sms-voice
bun add @aws-sdk/client-polly
bun add @aws-sdk/client-pricing
bun add @aws-sdk/client-proton
bun add @aws-sdk/client-qldb
bun add @aws-sdk/client-qldb-session
bun add @aws-sdk/client-quicksight
bun add @aws-sdk/client-ram
bun add @aws-sdk/client-rbin
bun add @aws-sdk/client-rds
bun add @aws-sdk/client-redshift
bun add @aws-sdk/client-redshiftserverless
bun add @aws-sdk/client-rekognition
bun add @aws-sdk/client-resiliencehub
bun add @aws-sdk/client-resource-groups
bun add @aws-sdk/client-resource-groups-tagging-api
bun add @aws-sdk/client-robomaker
bun add @aws-sdk/client-rum
bun add @aws-sdk/client-s3
bun add @aws-sdk/client-sagemaker
bun add @aws-sdk/client-sagemaker-edge
bun add @aws-sdk/client-sagemaker-featurestore-runtime
bun add @aws-sdk/client-sagemaker-runtime
bun add @aws-sdk/client-savingsplans
bun add @aws-sdk/client-schemas
bun add @aws-sdk/client-secrets-manager
bun add @aws-sdk/client-securityhub
bun add @aws-sdk/client-serverlessapplicationrepository
bun add @aws-sdk/client-service-catalog-appregistry
bun add @aws-sdk/client-service-quotas
bun add @aws-sdk/client-servicediscovery
bun add @aws-sdk/client-ses
bun add @aws-sdk/client-sfn
bun add @aws-sdk/client-shield
bun add @aws-sdk/client-signer
bun add @aws-sdk/client-sms
bun add @aws-sdk/client-snow-device-management
bun add @aws-sdk/client-snowball
bun add @aws-sdk/client-sns
bun add @aws-sdk/client-sqs
bun add @aws-sdk/client-ssm
bun add @aws-sdk/client-ssm-contacts
bun add @aws-sdk/client-ssm-incidents
bun add @aws-sdk/client-sso
bun add @aws-sdk/client-sso-admin
bun add @aws-sdk/client-sso-oidc
bun add @aws-sdk/client-storage-gateway
bun add @aws-sdk/client-sts
bun add @aws-sdk/client-support
bun add @aws-sdk/client-swf
bun add @aws-sdk/client-synthetics
bun add @aws-sdk/client-textract
bun add @aws-sdk/client-timestream-query
bun add @aws-sdk/client-timestream-write
bun add @aws-sdk/client-transcribe
bun add @aws-sdk/client-transcribe-streaming
bun add @aws-sdk/client-transfer
bun add @aws-sdk/client-translate
bun add @aws-sdk/client-voice-id
bun add @aws-sdk/client-waf
bun add @aws-sdk/client-waf-regional
bun add @aws-sdk/client-wellarchitected
bun add @aws-sdk/client-wisdom
bun add @aws-sdk/client-workdocs
bun add @aws-sdk/client-worklink
bun add @aws-sdk/client-workmail
bun add @aws-sdk/client-workmailmessageflow
bun add @aws-sdk/client-workspaces
bun add @aws-sdk/client-workspaces-web
bun add @aws-sdk/client-xray
bun add @aws-sdk/credential-providers
bun add @azure/app-configuration
bun add @azure/arm-advisor
bun add @azure/arm-analysisservices
bun add @azure/arm-apimanagement
bun add @azure/arm-app": "1.
bun add @azure/arm-appconfiguration
bun add @azure/arm-appcontainers
bun add @azure/arm-appinsights
bun add @azure/arm-appplatform
bun add @azure/arm-appservice
bun add @azure/arm-attestation
bun add @azure/arm-authorization
bun add @azure/arm-automanage
bun add @azure/arm-automation
bun add @azure/arm-avs
bun add @azure/arm-azureadexternalidentities
bun add @azure/arm-azurestack
bun add @azure/arm-azurestackhci
bun add @azure/arm-batch
bun add @azure/arm-batchai
bun add @azure/arm-billing
bun add @azure/arm-billingbenefits
bun add @azure/arm-botservice
bun add @azure/arm-cdn
bun add @azure/arm-changeanalysis
bun add @azure/arm-changes
bun add @azure/arm-chaos
bun add @azure/arm-cognitiveservices
bun add @azure/arm-commerce
bun add @azure/arm-commitmentplans
bun add @azure/arm-communication
bun add @azure/arm-compute
bun add @azure/arm-confidentialledger
bun add @azure/arm-confluent
bun add @azure/arm-consumption
bun add @azure/arm-containerinstance
bun add @azure/arm-containerregistry
bun add @azure/arm-containerservice
bun add @azure/arm-cosmosdb
bun add @azure/arm-customerinsights
bun add @azure/arm-dashboard
bun add @azure/arm-databox
bun add @azure/arm-databoxedge
bun add @azure/arm-databricks
bun add @azure/arm-datacatalog
bun add @azure/arm-datadog
bun add @azure/arm-datafactory
bun add @azure/arm-datalake-analytics
bun add @azure/arm-datamigration
bun add @azure/arm-deploymentmanager
bun add @azure/arm-desktopvirtualization
bun add @azure/arm-deviceprovisioningservices
bun add @azure/arm-deviceupdate
bun add @azure/arm-devspaces
bun add @azure/arm-devtestlabs
bun add @azure/arm-digitaltwins
bun add @azure/arm-dns
bun add @azure/arm-dnsresolver
bun add @azure/arm-domainservices
bun add @azure/arm-dynatrace
bun add @azure/arm-edgegateway
bun add @azure/arm-education": "1.
bun add @azure/arm-eventgrid
bun add @azure/arm-eventhub
bun add @azure/arm-extendedlocation": "1.
bun add @azure/arm-features
bun add @azure/arm-frontdoor
bun add @azure/arm-hanaonazure
bun add @azure/arm-hardwaresecuritymodules
bun add @azure/arm-hdinsight
bun add @azure/arm-healthbot
bun add @azure/arm-healthcareapis
bun add @azure/arm-hybridcompute
bun add @azure/arm-hybridkubernetes
bun add @azure/arm-imagebuilder
bun add @azure/arm-iotcentral
bun add @azure/arm-iothub
bun add @azure/arm-iotspaces
bun add @azure/arm-keyvault
bun add @azure/arm-kubernetesconfiguration
bun add @azure/arm-kusto
bun add @azure/arm-labservices
bun add @azure/arm-links
bun add @azure/arm-loadtestservice": "1.
bun add @azure/arm-locks
bun add @azure/arm-logic
bun add @azure/arm-machinelearning
bun add @azure/arm-machinelearningcompute
bun add @azure/arm-machinelearningexperimentation
bun add @azure/arm-machinelearningservices
bun add @azure/arm-managedapplications
bun add @azure/arm-managementgroups
bun add @azure/arm-managementpartner
bun add @azure/arm-maps
bun add @azure/arm-mariadb
bun add @azure/arm-marketplaceordering
bun add @azure/arm-mediaservices
bun add @azure/arm-migrate
bun add @azure/arm-mixedreality
bun add @azure/arm-mobilenetwork
bun add @azure/arm-monitor
bun add @azure/arm-msi
bun add @azure/arm-mysql
bun add @azure/arm-mysql-flexible
bun add @azure/arm-netapp
bun add @azure/arm-network
bun add @azure/arm-notificationhubs
bun add @azure/arm-oep": "1.
bun add @azure/arm-operationalinsights
bun add @azure/arm-operations
bun add @azure/arm-orbital
bun add @azure/arm-peering
bun add @azure/arm-policy
bun add @azure/arm-policyinsights
bun add @azure/arm-portal": "1.
bun add @azure/arm-postgresql
bun add @azure/arm-postgresql-flexible
bun add @azure/arm-powerbidedicated
bun add @azure/arm-powerbiembedded
bun add @azure/arm-privatedns
bun add @azure/arm-purview
bun add @azure/arm-quota
bun add @azure/arm-recoveryservices
bun add @azure/arm-recoveryservices-siterecovery
bun add @azure/arm-recoveryservicesbackup
bun add @azure/arm-rediscache
bun add @azure/arm-redisenterprisecache
bun add @azure/arm-relay
bun add @azure/arm-reservations
bun add @azure/arm-resourcegraph
bun add @azure/arm-resourcehealth
bun add @azure/arm-resourcemover
bun add @azure/arm-resources
bun add @azure/arm-resources-subscriptions
bun add @azure/arm-scvmm": "1.
bun add @azure/arm-search
bun add @azure/arm-security
bun add @azure/arm-securityinsight": "1.
bun add @azure/arm-serialconsole
bun add @azure/arm-servicebus
bun add @azure/arm-servicefabric
bun add @azure/arm-servicefabricmesh
bun add @azure/arm-servicelinker
bun add @azure/arm-servicemap
bun add @azure/arm-signalr
bun add @azure/arm-sql
bun add @azure/arm-sqlvirtualmachine
bun add @azure/arm-storage
bun add @azure/arm-storagecache
bun add @azure/arm-storageimportexport
bun add @azure/arm-storagesync
bun add @azure/arm-streamanalytics
bun add @azure/arm-subscriptions
bun add @azure/arm-support
bun add @azure/arm-synapse
bun add @azure/arm-template": "1.
bun add @azure/arm-templatespecs
bun add @azure/arm-timeseriesinsights
bun add @azure/arm-trafficmanager
bun add @azure/arm-videoanalyzer": "1.
bun add @azure/arm-visualstudio
bun add @azure/arm-vmwarecloudsimple
bun add @azure/arm-webpubsub
bun add @azure/arm-webservices
bun add @azure/arm-workspaces
bun add @azure/core-client
bun add @azure/functions
bun add @azure/graph
bun add @azure/keyvault-secrets
bun add @azure/logger
bun add @azure/monitor-query
bun add @azure/storage-blob
bun add @bitwarden/sdk-napi
bun add @google-cloud/appgateways
bun add @google-cloud/artifact-registry
bun add @google-cloud/assured-workloads
bun add @google-cloud/batch
bun add @google-cloud/billing
bun add @google-cloud/certificate-manager
bun add @google-cloud/compute
bun add @google-cloud/container
bun add @google-cloud/deploy
bun add @google-cloud/dns
bun add @google-cloud/domains
bun add @google-cloud/kms
bun add @google-cloud/kms-inventory
bun add @google-cloud/lineage
bun add @google-cloud/local-auth
bun add @google-cloud/managed-identities
bun add @google-cloud/monitoring-dashboards
bun add @google-cloud/network-management
bun add @google-cloud/notebooks
bun add @google-cloud/orchestration-airflow
bun add @google-cloud/org-policy
bun add @google-cloud/os-config
bun add @google-cloud/redis
bun add @google-cloud/resource-manager
bun add @google-cloud/resource-settings
bun add @google-cloud/retail
bun add @google-cloud/secret-manager
bun add @google-cloud/security-private-ca
bun add @google-cloud/service-directory
bun add @google-cloud/service-usage
bun add @google-cloud/storage
bun add @google-cloud/storageinsights
bun add @google-cloud/tasks
bun add @google-cloud/vmwareengine
bun add @google-cloud/vpc-access
bun add @google-cloud/web-security-scanner
bun add @google-cloud/workflows
bun add @google-cloud/workstations
bun add @kubernetes/client-node
bun add @microsoft/microsoft-graph-client
bun add @microsoft/teams-js
bun add @octokit/core
bun add @types/pg
bun add aws-lambda
bun add axios
bun add cfonts
bun add dotenv
bun add extract-zip
bun add google-auth-library
bun add googleapis
bun add helm-ts
bun add js-yaml
bun add jsdom
bun add jsome
bun add moment
bun add mongoose
bun add mysql2
bun add node-config-ts
bun add nodemailer
bun add octokit
bun add pg
bun add request
bun add tslog
bun add twilio
bun add uuid
# dev dependencies
bun add @azure/identity
bun add @jazzer.js/core
bun add @semantic-release/changelog
bun add @semantic-release/commit-analyzer
bun add @semantic-release/exec
bun add @semantic-release/git
bun add @semantic-release/github
bun add @semantic-release/npm
bun add @semantic-release/release-notes-generator
bun add @types/aws-lambda
bun add @types/azure
bun add @types/chai
bun add @types/glob
bun add @types/js-yaml
bun add @types/minimatch
bun add @types/mocha
bun add @types/node
bun add @types/rimraf
bun add chai
bun add mocha
bun add nodemon
bun add rimraf
bun add semantic-release
bun add ts-node
bun add typescript
bun add pino