// This file was auto-generated by updateCapability.service.ts
// NOTE: require() is used instead of `import * as` on purpose: Bun's bundler
// synthesizes ESM namespace objects with getters that can reference renamed or
// dropped symbols in compiled binaries, which crashes export enumeration in
// extractObjectsOrFunctions() (ReferenceError). The CommonJS build of the SDKs
// exposes plain export objects that survive bundling.

const clientsso = require('@aws-sdk/client-sso');
const clientsts = require('@aws-sdk/client-sts');
const clientdynamodb = require('@aws-sdk/client-dynamodb');
const clientcognitoidentity = require('@aws-sdk/client-cognito-identity');
const clientsqs = require('@aws-sdk/client-sqs');
const clientkinesis = require('@aws-sdk/client-kinesis');
const clientfirehose = require('@aws-sdk/client-firehose');
const clientcloudwatchlogs = require('@aws-sdk/client-cloudwatch-logs');
const clienttranslate = require('@aws-sdk/client-translate');
const clienttextract = require('@aws-sdk/client-textract');
const clientpinpoint = require('@aws-sdk/client-pinpoint');
const clientrekognition = require('@aws-sdk/client-rekognition');
const clientpolly = require('@aws-sdk/client-polly');
const clientcomprehend = require('@aws-sdk/client-comprehend');
const clientlocation = require('@aws-sdk/client-location');
const clientpersonalizeevents = require('@aws-sdk/client-personalize-events');
const clientsecretsmanager = require('@aws-sdk/client-secrets-manager');
const clientsns = require('@aws-sdk/client-sns');
const clientssm = require('@aws-sdk/client-ssm');
const clientlambda = require('@aws-sdk/client-lambda');
const clientses = require('@aws-sdk/client-ses');
const clienteventbridge = require('@aws-sdk/client-eventbridge');
const clientecr = require('@aws-sdk/client-ecr');
const clientkms = require('@aws-sdk/client-kms');
const clientcognitoidentityprovider = require('@aws-sdk/client-cognito-identity-provider');
const clientiam = require('@aws-sdk/client-iam');
const clientcloudwatch = require('@aws-sdk/client-cloudwatch');
const clientsfn = require('@aws-sdk/client-sfn');
const clientcloudformation = require('@aws-sdk/client-cloudformation');
const clientapigateway = require('@aws-sdk/client-api-gateway');
const clientecs = require('@aws-sdk/client-ecs');
const clientcloudfront = require('@aws-sdk/client-cloudfront');
const clientrds = require('@aws-sdk/client-rds');
const clientcodebuild = require('@aws-sdk/client-codebuild');
const clientacm = require('@aws-sdk/client-acm');
const clientcodepipeline = require('@aws-sdk/client-codepipeline');
const clientathena = require('@aws-sdk/client-athena');
const clientelasticache = require('@aws-sdk/client-elasticache');
const clienttimestreamwrite = require('@aws-sdk/client-timestream-write');
const clientcodedeploy = require('@aws-sdk/client-codedeploy');
const clienttimestreamquery = require('@aws-sdk/client-timestream-query');
const clientxray = require('@aws-sdk/client-xray');
const clientiot = require('@aws-sdk/client-iot');
const clienteks = require('@aws-sdk/client-eks');
const clientopensearch = require('@aws-sdk/client-opensearch');
const clientcodeartifact = require('@aws-sdk/client-codeartifact');
const clientapigatewaymanagementapi = require('@aws-sdk/client-apigatewaymanagementapi');
const clientglue = require('@aws-sdk/client-glue');
const clientresourcegroups = require('@aws-sdk/client-resource-groups');
const clientcodecommit = require('@aws-sdk/client-codecommit');
const clientbatch = require('@aws-sdk/client-batch');
const clientredshift = require('@aws-sdk/client-redshift');
const clientmediaconvert = require('@aws-sdk/client-mediaconvert');
const clientappconfig = require('@aws-sdk/client-appconfig');
const clientcloudtrail = require('@aws-sdk/client-cloudtrail');
const clientquicksight = require('@aws-sdk/client-quicksight');
const clientdynamodbstreams = require('@aws-sdk/client-dynamodb-streams');
const clientelasticbeanstalk = require('@aws-sdk/client-elastic-beanstalk');
const clientkinesisvideo = require('@aws-sdk/client-kinesis-video');
const clientivs = require('@aws-sdk/client-ivs');
const clientappsync = require('@aws-sdk/client-appsync');
const clientemr = require('@aws-sdk/client-emr');
const clientservicediscovery = require('@aws-sdk/client-servicediscovery');
const clienttranscribe = require('@aws-sdk/client-transcribe');
const clientssooidc = require('@aws-sdk/client-sso-oidc');
const clientorganizations = require('@aws-sdk/client-organizations');
const clientfis = require('@aws-sdk/client-fis');
const clientmedialive = require('@aws-sdk/client-medialive');
const clientkafka = require('@aws-sdk/client-kafka');
const clientconnect = require('@aws-sdk/client-connect');
const clientamplify = require('@aws-sdk/client-amplify');
const clientrum = require('@aws-sdk/client-rum');
const clienttransfer = require('@aws-sdk/client-transfer');
const clientebs = require('@aws-sdk/client-ebs');
const clientdocdb = require('@aws-sdk/client-docdb');
const clientinspector = require('@aws-sdk/client-inspector');
const clientmediapackage = require('@aws-sdk/client-mediapackage');
const clientmwaa = require('@aws-sdk/client-mwaa');
const clientevidently = require('@aws-sdk/client-evidently');
const clientmarketplacemetering = require('@aws-sdk/client-marketplace-metering');
const clientecrpublic = require('@aws-sdk/client-ecr-public');
const clientsagemakerruntime = require('@aws-sdk/client-sagemaker-runtime');
const clientiotdataplane = require('@aws-sdk/client-iot-data-plane');
const clientchime = require('@aws-sdk/client-chime');
const clientkinesisvideosignaling = require('@aws-sdk/client-kinesis-video-signaling');
const clientchimesdkmessaging = require('@aws-sdk/client-chime-sdk-messaging');
const clientsagemaker = require('@aws-sdk/client-sagemaker');
const clientcloudcontrol = require('@aws-sdk/client-cloudcontrol');
const clientbackup = require('@aws-sdk/client-backup');
const clienttranscribestreaming = require('@aws-sdk/client-transcribe-streaming');
const clientautoscaling = require('@aws-sdk/client-auto-scaling');
const clientmq = require('@aws-sdk/client-mq');
const clientcostexplorer = require('@aws-sdk/client-cost-explorer');
const clientram = require('@aws-sdk/client-ram');
const clientsecurityhub = require('@aws-sdk/client-securityhub');
const clientschemas = require('@aws-sdk/client-schemas');
const clientappflow = require('@aws-sdk/client-appflow');
const clientqldb = require('@aws-sdk/client-qldb');
const clientapprunner = require('@aws-sdk/client-apprunner');
const clientappstream = require('@aws-sdk/client-appstream');
const clientdatasync = require('@aws-sdk/client-datasync');
const clienthealthlake = require('@aws-sdk/client-healthlake');
const clientimagebuilder = require('@aws-sdk/client-imagebuilder');
const clientmediaconnect = require('@aws-sdk/client-mediaconnect');
const clientguardduty = require('@aws-sdk/client-guardduty');
const clientcloudsearchdomain = require('@aws-sdk/client-cloudsearch-domain');
const clientcloudwatchevents = require('@aws-sdk/client-cloudwatch-events');
const clientaccessanalyzer = require('@aws-sdk/client-accessanalyzer');
const clientelastictranscoder = require('@aws-sdk/client-elastic-transcoder');
const clientpricing = require('@aws-sdk/client-pricing');
const clientserverlessapplicationrepository = require('@aws-sdk/client-serverlessapplicationrepository');
const clientworkspaces = require('@aws-sdk/client-workspaces');
const clientresourcegroupstaggingapi = require('@aws-sdk/client-resource-groups-tagging-api');
const clientefs = require('@aws-sdk/client-efs');
const clientworkmail = require('@aws-sdk/client-workmail');
const clientdevicefarm = require('@aws-sdk/client-device-farm');
const clientglacier = require('@aws-sdk/client-glacier');
const clientcomprehendmedical = require('@aws-sdk/client-comprehendmedical');
const clientlakeformation = require('@aws-sdk/client-lakeformation');
const clientpersonalizeruntime = require('@aws-sdk/client-personalize-runtime');
const clientfsx = require('@aws-sdk/client-fsx');
const clientchimesdkmeetings = require('@aws-sdk/client-chime-sdk-meetings');
const clientiotsitewise = require('@aws-sdk/client-iotsitewise');
const clientforecast = require('@aws-sdk/client-forecast');
const clientgamelift = require('@aws-sdk/client-gamelift');
const clientsynthetics = require('@aws-sdk/client-synthetics');
const clientlightsail = require('@aws-sdk/client-lightsail');
const clientneptune = require('@aws-sdk/client-neptune');
const clientcloudsearch = require('@aws-sdk/client-cloudsearch');
const clientwaf = require('@aws-sdk/client-waf');
const clientservicequotas = require('@aws-sdk/client-service-quotas');
const clientidentitystore = require('@aws-sdk/client-identitystore');
const clientsigner = require('@aws-sdk/client-signer');
const clientpersonalize = require('@aws-sdk/client-personalize');
const clientkendra = require('@aws-sdk/client-kendra');
const clientemrcontainers = require('@aws-sdk/client-emr-containers');
const clientmemorydb = require('@aws-sdk/client-memorydb');
const clientamplifybackend = require('@aws-sdk/client-amplifybackend');
const clientelasticloadbalancing = require('@aws-sdk/client-elastic-load-balancing');
const clientiotsecuretunneling = require('@aws-sdk/client-iotsecuretunneling');
const clienthealth = require('@aws-sdk/client-health');
const clientaccount = require('@aws-sdk/client-account');
const clientgrafana = require('@aws-sdk/client-grafana');
const clientdetective = require('@aws-sdk/client-detective');
const clientproton = require('@aws-sdk/client-proton');
const clientqldbsession = require('@aws-sdk/client-qldb-session');
const clientiottwinmaker = require('@aws-sdk/client-iottwinmaker');
const clientdrs = require('@aws-sdk/client-drs');
const clientwisdom = require('@aws-sdk/client-wisdom');
const clientamplifyuibuilder = require('@aws-sdk/client-amplifyuibuilder');
const clientkafkaconnect = require('@aws-sdk/client-kafkaconnect');
const clientpanorama = require('@aws-sdk/client-panorama');
const clientbraket = require('@aws-sdk/client-braket');
const clientrbin = require('@aws-sdk/client-rbin');
const clientfinspace = require('@aws-sdk/client-finspace');
const clientresiliencehub = require('@aws-sdk/client-resiliencehub');
const clientauditmanager = require('@aws-sdk/client-auditmanager');
const clientlookoutvision = require('@aws-sdk/client-lookoutvision');
const clientnimble = require('@aws-sdk/client-nimble');
const clientamp = require('@aws-sdk/client-amp');
const clientlookoutmetrics = require('@aws-sdk/client-lookoutmetrics');
const clientmigrationhubstrategy = require('@aws-sdk/client-migrationhubstrategy');
const clientlookoutequipment = require('@aws-sdk/client-lookoutequipment');
const clientiotdeviceadvisor = require('@aws-sdk/client-iotdeviceadvisor');
const clientapplicationcostprofiler = require('@aws-sdk/client-applicationcostprofiler');
const clientkeyspaces = require('@aws-sdk/client-keyspaces');
const clientdataexchange = require('@aws-sdk/client-dataexchange');
const clientbillingconductor = require('@aws-sdk/client-billingconductor');
const clientmgn = require('@aws-sdk/client-mgn');
const clientmediastore = require('@aws-sdk/client-mediastore');
const clientgamesparks = require('@aws-sdk/client-gamesparks');
const clientdatabrew = require('@aws-sdk/client-databrew');
const clientpinpointemail = require('@aws-sdk/client-pinpoint-email');
const clientopsworks = require('@aws-sdk/client-opsworks');
const clientappintegrations = require('@aws-sdk/client-appintegrations');
const clientivschat = require('@aws-sdk/client-ivschat');
const clientwellarchitected = require('@aws-sdk/client-wellarchitected');
const clientforecastquery = require('@aws-sdk/client-forecastquery');
const clientiotfleethub = require('@aws-sdk/client-iotfleethub');
const clientmturk = require('@aws-sdk/client-mturk');
const clientgreengrass = require('@aws-sdk/client-greengrass');
const clientchimesdkidentity = require('@aws-sdk/client-chime-sdk-identity');
const clienthoneycode = require('@aws-sdk/client-honeycode');
const clientsavingsplans = require('@aws-sdk/client-savingsplans');
const clientclouddirectory = require('@aws-sdk/client-clouddirectory');
const clientshield = require('@aws-sdk/client-shield');
const clientfms = require('@aws-sdk/client-fms');
const clientdax = require('@aws-sdk/client-dax');
const clientswf = require('@aws-sdk/client-swf');
const clientopsworkscm = require('@aws-sdk/client-opsworkscm');
const clientmediatailor = require('@aws-sdk/client-mediatailor');
const clientnetworkmanager = require('@aws-sdk/client-networkmanager');
const clientsms = require('@aws-sdk/client-sms');
const clientdlm = require('@aws-sdk/client-dlm');
const clientoutposts = require('@aws-sdk/client-outposts');
const clientworklink = require('@aws-sdk/client-worklink');
const clientconnectparticipant = require('@aws-sdk/client-connectparticipant');
const clientiotanalytics = require('@aws-sdk/client-iotanalytics');
const clientbudgets = require('@aws-sdk/client-budgets');
const clientfrauddetector = require('@aws-sdk/client-frauddetector');
const clientdatapipeline = require('@aws-sdk/client-data-pipeline');
const clientmobile = require('@aws-sdk/client-mobile');
const clientcodestar = require('@aws-sdk/client-codestar');
const clientiotthingsgraph = require('@aws-sdk/client-iotthingsgraph');
const clientworkmailmessageflow = require('@aws-sdk/client-workmailmessageflow');
const clientsnowball = require('@aws-sdk/client-snowball');
const clientmacie = require('@aws-sdk/client-macie');
const clientcodeguruprofiler = require('@aws-sdk/client-codeguruprofiler');
const clientcloudhsm = require('@aws-sdk/client-cloudhsm');
const clientrobomaker = require('@aws-sdk/client-robomaker');
const clientpi = require('@aws-sdk/client-pi');
const clientworkdocs = require('@aws-sdk/client-workdocs');
const clientsupport = require('@aws-sdk/client-support');
const clientmanagedblockchain = require('@aws-sdk/client-managedblockchain');
const clientgroundstation = require('@aws-sdk/client-groundstation');
const clientnetworkfirewall = require('@aws-sdk/client-network-firewall');
const clientcustomerprofiles = require('@aws-sdk/client-customer-profiles');
const clientappmesh = require('@aws-sdk/client-app-mesh');
const clientacmpca = require('@aws-sdk/client-acm-pca');
const clientssoadmin = require('@aws-sdk/client-sso-admin');
const clientglobalaccelerator = require('@aws-sdk/client-global-accelerator');
const clientmediapackagevod = require('@aws-sdk/client-mediapackage-vod');
const clientbackupgateway = require('@aws-sdk/client-backup-gateway');
const clientvoiceid = require('@aws-sdk/client-voice-id');
const clientdevopsguru = require('@aws-sdk/client-devops-guru');
const clientworkspacesweb = require('@aws-sdk/client-workspaces-web');
const clientssmincidents = require('@aws-sdk/client-ssm-incidents');
const clientconnectcampaigns = require('@aws-sdk/client-connectcampaigns');
const clientdirectconnect = require('@aws-sdk/client-direct-connect');
const clientconnectcontactlens = require('@aws-sdk/client-connect-contact-lens');
const clientssmcontacts = require('@aws-sdk/client-ssm-contacts');
const clientapplicationautoscaling = require('@aws-sdk/client-application-auto-scaling');
const clientcognitosync = require('@aws-sdk/client-cognito-sync');
const clientcodestarconnections = require('@aws-sdk/client-codestar-connections');
const clientmachinelearning = require('@aws-sdk/client-machine-learning');
const clientapplicationinsights = require('@aws-sdk/client-application-insights');
const clientlicensemanager = require('@aws-sdk/client-license-manager');
const clientstoragegateway = require('@aws-sdk/client-storage-gateway');
const clientiotevents = require('@aws-sdk/client-iot-events');
const clientmigrationhubconfig = require('@aws-sdk/client-migrationhub-config');
const clientkinesisanalytics = require('@aws-sdk/client-kinesis-analytics');
const clientcodegurureviewer = require('@aws-sdk/client-codeguru-reviewer');
const clientwafregional = require('@aws-sdk/client-waf-regional');
const clientelasticinference = require('@aws-sdk/client-elastic-inference');
const clientcodestarnotifications = require('@aws-sdk/client-codestar-notifications');
const clientmigrationhub = require('@aws-sdk/client-migration-hub');
const clientcomputeoptimizer = require('@aws-sdk/client-compute-optimizer');
const clientchimesdkmediapipelines = require('@aws-sdk/client-chime-sdk-media-pipelines');
const clientiotwireless = require('@aws-sdk/client-iot-wireless');
const clientsagemakeredge = require('@aws-sdk/client-sagemaker-edge');
const clientemrserverless = require('@aws-sdk/client-emr-serverless');
const clientsnowdevicemanagement = require('@aws-sdk/client-snow-device-management');
const clientpinpointsmsvoice = require('@aws-sdk/client-pinpoint-sms-voice');
const clientkinesisvideomedia = require('@aws-sdk/client-kinesis-video-media');
const clientalexaforbusiness = require('@aws-sdk/client-alexa-for-business');
const clientiotjobsdataplane = require('@aws-sdk/client-iot-jobs-data-plane');
const clientmarketplacecommerceanalytics = require('@aws-sdk/client-marketplace-commerce-analytics');
const clientautoscalingplans = require('@aws-sdk/client-auto-scaling-plans');
const clientservicecatalogappregistry = require('@aws-sdk/client-service-catalog-appregistry');
const clientsagemakerfeaturestoreruntime = require('@aws-sdk/client-sagemaker-featurestore-runtime');
const clientkinesisvideoarchivedmedia = require('@aws-sdk/client-kinesis-video-archived-media');
const clientmigrationhubrefactorspaces = require('@aws-sdk/client-migration-hub-refactor-spaces');
const clientredshiftserverless = require('@aws-sdk/client-redshiftserverless');
const clientcommander = require('@aws-sdk/client-commander');
const clientec2 = require('@aws-sdk/client-ec2');
const clients3 = require('@aws-sdk/client-s3');
export {
clientec2,
clients3,
clientsso,
clientsts,
clientdynamodb,
clientcognitoidentity,
clientsqs,
clientkinesis,
clientfirehose,
clientcloudwatchlogs,
clienttranslate,
clienttextract,
clientpinpoint,
clientrekognition,
clientpolly,
clientcomprehend,
clientlocation,
clientpersonalizeevents,
clientsecretsmanager,
clientsns,
clientssm,
clientlambda,
clientses,
clienteventbridge,
clientecr,
clientkms,
clientcognitoidentityprovider,
clientiam,
clientcloudwatch,
clientsfn,
clientcloudformation,
clientapigateway,
clientecs,
clientcloudfront,
clientrds,
clientcodebuild,
clientacm,
clientcodepipeline,
clientathena,
clientelasticache,
clienttimestreamwrite,
clientcodedeploy,
clienttimestreamquery,
clientxray,
clientiot,
clienteks,
clientopensearch,
clientcodeartifact,
clientapigatewaymanagementapi,
clientglue,
clientresourcegroups,
clientcodecommit,
clientbatch,
clientredshift,
clientmediaconvert,
clientappconfig,
clientcloudtrail,
clientquicksight,
clientdynamodbstreams,
clientelasticbeanstalk,
clientkinesisvideo,
clientivs,
clientappsync,
clientemr,
clientservicediscovery,
clienttranscribe,
clientssooidc,
clientorganizations,
clientfis,
clientmedialive,
clientkafka,
clientconnect,
clientamplify,
clientrum,
clienttransfer,
clientebs,
clientdocdb,
clientinspector,
clientmediapackage,
clientmwaa,
clientevidently,
clientmarketplacemetering,
clientecrpublic,
clientsagemakerruntime,
clientiotdataplane,
clientchime,
clientkinesisvideosignaling,
clientchimesdkmessaging,
clientsagemaker,
clientcloudcontrol,
clientbackup,
clienttranscribestreaming,
clientautoscaling,
clientmq,
clientcostexplorer,
clientram,
clientsecurityhub,
clientschemas,
clientappflow,
clientqldb,
clientapprunner,
clientappstream,
clientdatasync,
clienthealthlake,
clientimagebuilder,
clientmediaconnect,
clientguardduty,
clientcloudsearchdomain,
clientcloudwatchevents,
clientaccessanalyzer,
clientelastictranscoder,
clientpricing,
clientserverlessapplicationrepository,
clientworkspaces,
clientresourcegroupstaggingapi,
clientefs,
clientworkmail,
clientdevicefarm,
clientglacier,
clientcomprehendmedical,
clientlakeformation,
clientpersonalizeruntime,
clientfsx,
clientchimesdkmeetings,
clientiotsitewise,
clientforecast,
clientgamelift,
clientsynthetics,
clientlightsail,
clientneptune,
clientcloudsearch,
clientwaf,
clientservicequotas,
clientidentitystore,
clientsigner,
clientpersonalize,
clientkendra,
clientemrcontainers,
clientmemorydb,
clientamplifybackend,
clientelasticloadbalancing,
clientiotsecuretunneling,
clienthealth,
clientaccount,
clientgrafana,
clientdetective,
clientproton,
clientqldbsession,
clientiottwinmaker,
clientdrs,
clientwisdom,
clientamplifyuibuilder,
clientkafkaconnect,
clientpanorama,
clientbraket,
clientrbin,
clientfinspace,
clientresiliencehub,
clientauditmanager,
clientlookoutvision,
clientnimble,
clientamp,
clientlookoutmetrics,
clientmigrationhubstrategy,
clientlookoutequipment,
clientiotdeviceadvisor,
clientapplicationcostprofiler,
clientkeyspaces,
clientdataexchange,
clientbillingconductor,
clientmgn,
clientmediastore,
clientgamesparks,
clientdatabrew,
clientpinpointemail,
clientopsworks,
clientappintegrations,
clientivschat,
clientwellarchitected,
clientforecastquery,
clientiotfleethub,
clientmturk,
clientgreengrass,
clientchimesdkidentity,
clienthoneycode,
clientsavingsplans,
clientclouddirectory,
clientshield,
clientfms,
clientdax,
clientswf,
clientopsworkscm,
clientmediatailor,
clientnetworkmanager,
clientsms,
clientdlm,
clientoutposts,
clientworklink,
clientconnectparticipant,
clientiotanalytics,
clientbudgets,
clientfrauddetector,
clientdatapipeline,
clientmobile,
clientcodestar,
clientiotthingsgraph,
clientworkmailmessageflow,
clientsnowball,
clientmacie,
clientcodeguruprofiler,
clientcloudhsm,
clientrobomaker,
clientpi,
clientworkdocs,
clientsupport,
clientmanagedblockchain,
clientgroundstation,
clientnetworkfirewall,
clientcustomerprofiles,
clientappmesh,
clientacmpca,
clientssoadmin,
clientglobalaccelerator,
clientmediapackagevod,
clientbackupgateway,
clientvoiceid,
clientdevopsguru,
clientworkspacesweb,
clientssmincidents,
clientconnectcampaigns,
clientdirectconnect,
clientconnectcontactlens,
clientssmcontacts,
clientapplicationautoscaling,
clientcognitosync,
clientcodestarconnections,
clientmachinelearning,
clientapplicationinsights,
clientlicensemanager,
clientstoragegateway,
clientiotevents,
clientmigrationhubconfig,
clientkinesisanalytics,
clientcodegurureviewer,
clientwafregional,
clientelasticinference,
clientcodestarnotifications,
clientmigrationhub,
clientcomputeoptimizer,
clientchimesdkmediapipelines,
clientiotwireless,
clientsagemakeredge,
clientemrserverless,
clientsnowdevicemanagement,
clientpinpointsmsvoice,
clientkinesisvideomedia,
clientalexaforbusiness,
clientiotjobsdataplane,
clientmarketplacecommerceanalytics,
clientautoscalingplans,
clientservicecatalogappregistry,
clientsagemakerfeaturestoreruntime,
clientkinesisvideoarchivedmedia,
clientmigrationhubrefactorspaces,
clientredshiftserverless,
clientcommander};
