// This file was auto-generated by updateCapability.service.ts
// NOTE: require() is used instead of `import * as` on purpose: Bun's bundler
// synthesizes ESM namespace objects with getters that can reference renamed or
// dropped symbols in compiled binaries, which crashes export enumeration in
// extractClients() (ReferenceError). The CommonJS build of the SDKs exposes
// plain export objects that survive bundling.

const armresources = require('@azure/arm-resources');
const armsubscriptions = require('@azure/arm-subscriptions');
const armsql = require('@azure/arm-sql');
const armstorage = require('@azure/arm-storage');
const armappservice = require('@azure/arm-appservice');
const armmonitor = require('@azure/arm-monitor');
const armservicebus = require('@azure/arm-servicebus');
const armkeyvault = require('@azure/arm-keyvault');
const armcompute = require('@azure/arm-compute');
const armeventhub = require('@azure/arm-eventhub');
const armrediscache = require('@azure/arm-rediscache');
const armpostgresql = require('@azure/arm-postgresql');
const armmaps = require('@azure/arm-maps');
const armmariadb = require('@azure/arm-mariadb');
const armmediaservices = require('@azure/arm-mediaservices');
const armcontainerservice = require('@azure/arm-containerservice');
const armcontainerregistry = require('@azure/arm-containerregistry');
const armcosmosdb = require('@azure/arm-cosmosdb');
const armstreamanalytics = require('@azure/arm-streamanalytics');
const armconsumption = require('@azure/arm-consumption');
const armrecoveryservicesbackup = require('@azure/arm-recoveryservicesbackup');
const armlocks = require('@azure/arm-locks');
const armeventgrid = require('@azure/arm-eventgrid');
const armresourcessubscriptions = require('@azure/arm-resources-subscriptions');
const armpolicy = require('@azure/arm-policy');
const armiotcentral = require('@azure/arm-iotcentral');
const armdevtestlabs = require('@azure/arm-devtestlabs');
const armlogic = require('@azure/arm-logic');
const armdns = require('@azure/arm-dns');
const armpurview = require('@azure/arm-purview');
const armservicefabric = require('@azure/arm-servicefabric');
const armmanagedapplications = require('@azure/arm-managedapplications');
const armmsi = require('@azure/arm-msi');
const armbilling = require('@azure/arm-billing');
const armsearch = require('@azure/arm-search');
const armmanagementgroups = require('@azure/arm-managementgroups');
const armcdn = require('@azure/arm-cdn');
const armresourcehealth = require('@azure/arm-resourcehealth');
const armmachinelearningservices = require('@azure/arm-machinelearningservices');
const armprivatedns = require('@azure/arm-privatedns');
const armcontainerinstance = require('@azure/arm-containerinstance');
const armauthorization = require('@azure/arm-authorization');
const armkusto = require('@azure/arm-kusto');
const armpowerbiembedded = require('@azure/arm-powerbiembedded');
const armhybridcompute = require('@azure/arm-hybridcompute');
const armsignalr = require('@azure/arm-signalr');
const armchangeanalysis = require('@azure/arm-changeanalysis');
const armattestation = require('@azure/arm-attestation');
const armimagebuilder = require('@azure/arm-imagebuilder');
const armmarketplaceordering = require('@azure/arm-marketplaceordering');
const armcommunication = require('@azure/arm-communication');
const armcognitiveservices = require('@azure/arm-cognitiveservices');
const armpolicyinsights = require('@azure/arm-policyinsights');
const armstoragecache = require('@azure/arm-storagecache');
const armfrontdoor = require('@azure/arm-frontdoor');
const armmixedreality = require('@azure/arm-mixedreality');
const armpeering = require('@azure/arm-peering');
const armfeatures = require('@azure/arm-features');
const armnetapp = require('@azure/arm-netapp');
const armvmwarecloudsimple = require('@azure/arm-vmwarecloudsimple');
const armhdinsight = require('@azure/arm-hdinsight');
const armstorageimportexport = require('@azure/arm-storageimportexport');
const armwebservices = require('@azure/arm-webservices');
const armstoragesync = require('@azure/arm-storagesync');
const armpowerbidedicated = require('@azure/arm-powerbidedicated');
const armmanagementpartner = require('@azure/arm-managementpartner');
const armdatacatalog = require('@azure/arm-datacatalog');
const armmigrate = require('@azure/arm-migrate');
const armbatch = require('@azure/arm-batch');
const armserialconsole = require('@azure/arm-serialconsole');
const armredisenterprisecache = require('@azure/arm-redisenterprisecache');
const armrelay = require('@azure/arm-relay');
const armtrafficmanager = require('@azure/arm-trafficmanager');
const armdomainservices = require('@azure/arm-domainservices');
const armpostgresqlflexible = require('@azure/arm-postgresql-flexible');
const armrecoveryservicessiterecovery = require('@azure/arm-recoveryservices-siterecovery');
const armappinsights = require('@azure/arm-appinsights');
const armappplatform = require('@azure/arm-appplatform');
const armoperations = require('@azure/arm-operations');
const armkubernetesconfiguration = require('@azure/arm-kubernetesconfiguration');
const armappconfiguration = require('@azure/arm-appconfiguration');
const armlabservices = require('@azure/arm-labservices');
const armhanaonazure = require('@azure/arm-hanaonazure');
const armazurestack = require('@azure/arm-azurestack');
const armvisualstudio = require('@azure/arm-visualstudio');
const armdatabox = require('@azure/arm-databox');
const armmachinelearningcompute = require('@azure/arm-machinelearningcompute');
const armdatamigration = require('@azure/arm-datamigration');
const armdeploymentmanager = require('@azure/arm-deploymentmanager');
const armdatalakeanalytics = require('@azure/arm-datalake-analytics');
const armiotspaces = require('@azure/arm-iotspaces');
const armbatchai = require('@azure/arm-batchai');
const armvideoanalyzer = require('@azure/arm-videoanalyzer');
const armquota = require('@azure/arm-quota');
const armportal = require('@azure/arm-portal');
const armorbital = require('@azure/arm-orbital');
const armdesktopvirtualization = require('@azure/arm-desktopvirtualization');
const armloadtestservice = require('@azure/arm-loadtestservice');
const armextendedlocation = require('@azure/arm-extendedlocation');
const armmachinelearningexperimentation = require('@azure/arm-machinelearningexperimentation');
const armservicefabricmesh = require('@azure/arm-servicefabricmesh');
const armcommitmentplans = require('@azure/arm-commitmentplans');
const armdnsresolver = require('@azure/arm-dnsresolver');
const armedgegateway = require('@azure/arm-edgegateway');
const armmobilenetwork = require('@azure/arm-mobilenetwork');
const armnetwork = require('@azure/arm-network');
const armsynapse = require('@azure/arm-synapse');
const armmysql = require('@azure/arm-mysql');
const armsecurity = require('@azure/arm-security');
const armbotservice = require('@azure/arm-botservice');
const armtemplatespecs = require('@azure/arm-templatespecs');
const armlinks = require('@azure/arm-links');
const armresourcemover = require('@azure/arm-resourcemover');
const armavs = require('@azure/arm-avs');
const armdataboxedge = require('@azure/arm-databoxedge');
const armdatadog = require('@azure/arm-datadog');
const armiothub = require('@azure/arm-iothub');
const armazurestackhci = require('@azure/arm-azurestackhci');
const armsupport = require('@azure/arm-support');
const armworkspaces = require('@azure/arm-workspaces');
const armoperationalinsights = require('@azure/arm-operationalinsights');
const armautomation = require('@azure/arm-automation');
const armresourcegraph = require('@azure/arm-resourcegraph');
const armcommerce = require('@azure/arm-commerce');
const armconfluent = require('@azure/arm-confluent');
const armservicemap = require('@azure/arm-servicemap');
const armoep = require('@azure/arm-oep');
const armapimanagement = require('@azure/arm-apimanagement');
const armsqlvirtualmachine = require('@azure/arm-sqlvirtualmachine');
const armrecoveryservices = require('@azure/arm-recoveryservices');
const armdatabricks = require('@azure/arm-databricks');
const armdatafactory = require('@azure/arm-datafactory');
const armtimeseriesinsights = require('@azure/arm-timeseriesinsights');
const armdigitaltwins = require('@azure/arm-digitaltwins');
const armreservations = require('@azure/arm-reservations');
const armwebpubsub = require('@azure/arm-webpubsub');
const armnotificationhubs = require('@azure/arm-notificationhubs');
const armhybridkubernetes = require('@azure/arm-hybridkubernetes');
const armadvisor = require('@azure/arm-advisor');
const armhealthbot = require('@azure/arm-healthbot');
const armanalysisservices = require('@azure/arm-analysisservices');
const armhealthcareapis = require('@azure/arm-healthcareapis');
const armcustomerinsights = require('@azure/arm-customerinsights');
const armdeviceprovisioningservices = require('@azure/arm-deviceprovisioningservices');
const armdevspaces = require('@azure/arm-devspaces');
const armmysqlflexible = require('@azure/arm-mysql-flexible');
const armsecurityinsight = require('@azure/arm-securityinsight');
const armapp = require('@azure/arm-app');
const armtemplate = require('@azure/arm-template');
const armchanges = require('@azure/arm-changes');
const armservicelinker = require('@azure/arm-servicelinker');
const armmachinelearning = require('@azure/arm-machinelearning');
const armappcontainers = require('@azure/arm-appcontainers');
const armconfidentialledger = require('@azure/arm-confidentialledger');
const armdeviceupdate = require('@azure/arm-deviceupdate');
const armdynatrace = require('@azure/arm-dynatrace');
const armeducation = require('@azure/arm-education');
const armhardwaresecuritymodules = require('@azure/arm-hardwaresecuritymodules');
const armazureadexternalidentities = require('@azure/arm-azureadexternalidentities');
const armdashboard = require('@azure/arm-dashboard');
const armscvmm = require('@azure/arm-scvmm');
export {
armresources,
armsubscriptions,
armsql,
armstorage,
armappservice,
armmonitor,
armservicebus,
armkeyvault,
armcompute,
armeventhub,
armrediscache,
armpostgresql,
armmaps,
armmariadb,
armmediaservices,
armcontainerservice,
armcontainerregistry,
armcosmosdb,
armstreamanalytics,
armconsumption,
armrecoveryservicesbackup,
armlocks,
armeventgrid,
armresourcessubscriptions,
armpolicy,
armiotcentral,
armdevtestlabs,
armlogic,
armdns,
armpurview,
armservicefabric,
armmanagedapplications,
armmsi,
armbilling,
armsearch,
armmanagementgroups,
armcdn,
armresourcehealth,
armmachinelearningservices,
armprivatedns,
armcontainerinstance,
armauthorization,
armkusto,
armpowerbiembedded,
armhybridcompute,
armsignalr,
armchangeanalysis,
armattestation,
armimagebuilder,
armmarketplaceordering,
armcommunication,
armcognitiveservices,
armpolicyinsights,
armstoragecache,
armfrontdoor,
armmixedreality,
armpeering,
armfeatures,
armnetapp,
armvmwarecloudsimple,
armhdinsight,
armstorageimportexport,
armwebservices,
armstoragesync,
armpowerbidedicated,
armmanagementpartner,
armdatacatalog,
armmigrate,
armbatch,
armserialconsole,
armredisenterprisecache,
armrelay,
armtrafficmanager,
armdomainservices,
armpostgresqlflexible,
armrecoveryservicessiterecovery,
armappinsights,
armappplatform,
armoperations,
armkubernetesconfiguration,
armappconfiguration,
armlabservices,
armhanaonazure,
armazurestack,
armvisualstudio,
armdatabox,
armmachinelearningcompute,
armdatamigration,
armdeploymentmanager,
armdatalakeanalytics,
armiotspaces,
armbatchai,
armvideoanalyzer,
armquota,
armportal,
armorbital,
armdesktopvirtualization,
armloadtestservice,
armextendedlocation,
armmachinelearningexperimentation,
armservicefabricmesh,
armcommitmentplans,
armdnsresolver,
armedgegateway,
armmobilenetwork,
armnetwork,
armsynapse,
armmysql,
armsecurity,
armbotservice,
armtemplatespecs,
armlinks,
armresourcemover,
armavs,
armdataboxedge,
armdatadog,
armiothub,
armazurestackhci,
armsupport,
armworkspaces,
armoperationalinsights,
armautomation,
armresourcegraph,
armcommerce,
armconfluent,
armservicemap,
armoep,
armapimanagement,
armsqlvirtualmachine,
armrecoveryservices,
armdatabricks,
armdatafactory,
armtimeseriesinsights,
armdigitaltwins,
armreservations,
armwebpubsub,
armnotificationhubs,
armhybridkubernetes,
armadvisor,
armhealthbot,
armanalysisservices,
armhealthcareapis,
armcustomerinsights,
armdeviceprovisioningservices,
armdevspaces,
armmysqlflexible,
armsecurityinsight,
armapp,
armtemplate,
armchanges,
armservicelinker,
armmachinelearning,
armappcontainers,
armconfidentialledger,
armdeviceupdate,
armdynatrace,
armeducation,
armhardwaresecuritymodules,
armazureadexternalidentities,
armdashboard,
armscvmm};
