name: Push on Docker Registry (Dev)

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest
          cache: true
          cache-dependency-path: bun.lock

      - name: Install Dependencies
        run: bun i

      - name: Run tests
        run: bun run test

      - name: Run integration tests
        run: bun run test:integration

      - name: Get latest release version
        uses: rez0n/actions-github-release@794c12f5e8d629e6ca329cf2e2daeb0f0ce6a3ce # main
        id: get_latest_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "kexa-io/Kexa"
          type: "stable"

      - name: Print New Latest Version
        run: echo ${{ steps.get_latest_release.outputs.release }}


      - name: Login to Docker Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_NAME}}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME_KEXA }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD_KEXA }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Push on Docker Registry
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v6
        with:
          file: Dockerfile
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_NAME}}/kexa/kexa-dev:${{ steps.get_latest_release.outputs.release }}
            ${{ secrets.DOCKER_REGISTRY_NAME}}/kexa/kexa-dev:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

