name: versioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Verify Bun Installation
        run: |
          echo "Bun version: $(bun --version)"

      - name: Install Dependencies
        run: bun i

      - name: Run tests
        run: bun run test

      - name: Install Semantic Release and Plugins
        run: bun add -d semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec
      
      - name: Permissions for semantic-release
        run: chmod +x ./node_modules/.bin/semantic-release
      
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Run Semantic Release
        id: ver
        run: bun x semantic-release --debug   
        env:
          GH_TOKEN:  ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@794c12f5e8d629e6ca329cf2e2daeb0f0ce6a3ce # main
        id: get_latest_release
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: "kexa-io/Kexa"
          type: "stable"
      
      - name: Print New Latest Version
        run: echo ${{ steps.get_latest_release.outputs.release }}

      - name: Login to Docker Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_NAME}}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Push on Docker Registry
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        with:
          context: ./
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY_NAME}}/innovtech/kexa:${{ steps.get_latest_release.outputs.release }}
            ${{ secrets.DOCKER_REGISTRY_NAME}}/innovtech/kexa:latest